### ISSUE TITLE
Deadlock/Infinite wait in verifyTemplateAsync

### ISSUE THREAD

**Issue by mmitche** [jenkinsci/azure-slave-plugin#16]
I've seen a deadlock in verifyTemplateAsync a few times.  It blocks with the following callstack. 

I was under the impression this couldn't happen because of the timeout on the get call

```
"jenkins.util.Timer [#2]" Id=74 Group=main WAITING on java.util.concurrent.FutureTask@1954eb31
	at sun.misc.Unsafe.park(Native Method)
	-  waiting on java.util.concurrent.FutureTask@1954eb31
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:186)
	at java.util.concurrent.FutureTask.awaitDone(FutureTask.java:425)
	at java.util.concurrent.FutureTask.get(FutureTask.java:187)
	at java.util.concurrent.AbstractExecutorService.invokeAll(AbstractExecutorService.java:243)
	at com.microsoftopentechnologies.azure.AzureManagementServiceDelegate.verifyTemplateAsync(AzureManagementServiceDelegate.java:1631)
	at com.microsoftopentechnologies.azure.AzureManagementServiceDelegate.verifyTemplate(AzureManagementServiceDelegate.java:1579)
	at com.microsoftopentechnologies.azure.AzureSlaveTemplate.verifyTemplate(AzureSlaveTemplate.java:345)
	at com.microsoftopentechnologies.azure.AzureCloud.provision(AzureCloud.java:178)
	at hudson.slaves.NodeProvisioner$StandardStrategyImpl.apply(NodeProvisioner.java:701)
	at hudson.slaves.NodeProvisioner.update(NodeProvisioner.java:305)
	at hudson.slaves.NodeProvisioner.access$000(NodeProvisioner.java:58)
	at hudson.slaves.NodeProvisioner$NodeProvisionerInvoker.doRun(NodeProvisioner.java:798)
	at hudson.triggers.SafeTimerTask.run(SafeTimerTask.java:50)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)

	Number of locked synchronizers = 2
	- java.util.concurrent.ThreadPoolExecutor$Worker@7ecfce3f
	- java.util.concurrent.locks.ReentrantLock$NonfairSync@1d6fd628
```

**Comment by mmitche** [comment]
I see it.  In the code below, invokeAll does not immediately return.  The docs say that it returns when all tasks complete isDone is done for all tasks().  This use of the ExecutorService would only be valid if you simply called submit().  There should probably also be a call to shutdown() after making the invokeAll call, though I imagine that resources are reclaimed once the object is disposed of.  I'll prepare a PR.

```
List<Future<String>> validationResultList = executorService.invokeAll(verificationTaskList);

for(Future<String> validationResult : validationResultList) {

    try {
        // Get will block until time expires or until task completes
        String result = validationResult.get(60, TimeUnit.SECONDS);
        addValidationResultIfFailed(result, errors);
    } catch (ExecutionException executionException) {
        errors.add("Exception occured while validating temaplate "+executionException);
    } catch (TimeoutException timeoutException) {
        errors.add("Exception occured while validating temaplate "+timeoutException);
    }
}
```
